language: android
jdk: oraclejdk8
env:
  matrix:
    - ANDROID_TARGET=android-25  ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - android-sdk-license-.+

script: './travisBuilder.sh'